# Имя приложения
spring.application.name=online-store

# Настройки подключения к базе
spring.datasource.url=jdbc:postgresql://localhost:5432/store
spring.datasource.username=postgres
spring.datasource.password=87953

# Настройки Hibernate (библиотека для преобразования Java-объектов в таблицы данных и наоборот)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# jwt конфигурация
jwt.secret = your-super-secret-key-minimum-32-characters-longer-is-better

jwt.expiration = 86400000